Repository quadratic-funding/qfi, pull requests merged in 2022-04, with the labels that each got.

#82 Add a CI for contracts package and frontend
  .github/workflows/contracts-build.yml
  .github/workflows/contracts-coverage.yml
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-lighthouse.yml
  README.md
Labels: 13

#94 Change `tests/` imports from `build/` to `typechain/` folder
  .github/workflows/contracts-build.yml
  packages/contracts/package.json
  packages/contracts/tests/Unit/BaseRecipientRegistry.ts
  packages/contracts/tests/Unit/FundsManager.ts
  packages/contracts/tests/Unit/GrantRound.ts
  packages/contracts/tests/Unit/GrantRoundFactory.ts
  packages/contracts/tests/Unit/OptimisticRecipientRegistry.ts
  packages/contracts/tests/Unit/QFI.ts
  packages/contracts/tests/Unit/SimpleRecipientRegistry.ts
Labels: enhancement, 2

#91 Fix/subgraph
  packages/app/src/App.tsx
  packages/app/src/LandingPage.tsx
  packages/app/src/components/ColorModeSwitcher.tsx
  packages/app/src/components/Nav.tsx
  packages/app/src/context/DappContext.tsx
  packages/app/src/context/types.tsx
  packages/app/src/index.tsx
  packages/contracts/contracts/GrantRound.sol
  packages/contracts/contracts/QFI.sol
  packages/subgraph/abis/GrantRound.json
  packages/subgraph/abis/GrantRoundFactory.json
  packages/subgraph/abis/OptimisticRecipientRegistry.json
  packages/subgraph/abis/QFI.json
  packages/subgraph/package.json
  packages/subgraph/src/mapping/GrantRoundFactoryMapping.ts
  packages/subgraph/src/mapping/GrantRoundMapping.ts
  packages/subgraph/src/mapping/QFIMapping.ts
  packages/subgraph/src/mapping/RecipientRegistryMapping.ts
  packages/subgraph/src/utils/converter.ts
  packages/subgraph/subgraph.yaml
  packages/subgraph/tsconfig.json
  yarn.lock
Labels: bug, enhancement
